name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'
      - run: yarn install
      - run: make check
